name: Quests
main: me.blackvein.quests.Quests
version: ${project.version}-b${env.BUILD_NUMBER}
description: Player questing system
website: http://dev.bukkit.org/server-mods/quests/
dev-url: https://github.com/Blackvein/Quests/
authors: [Blackvein, HappyPikachu]
depend: [Vault]
softdepend: [Citizens, PhatLoots]
permissions:
    quests.quest:
        description: View current Quest objectives
        default: true
    quests.questinfo:
        description: View information about a Quest
        default: true
    quests.quests:
        description: View Quests help
        default: true
    quests.list:
        description: List Quests
        default: true
    quests.take:
        description: Accept a Quest via command
        default: true
    quests.quit:
        description: Quit current Quest
        default: true
    quests.stats:
        description: View Questing statistics
        default: true
    quests.top:
        description: View Questing leaderboards
        default: true
    quests.info:
        description: View plugin information
        default: true
    quests.journal:
        description: View Quest Journal
        default: true
    quests.admin:
        description: Base Questsadmin command
        default: op
    quests.admin.stats:
        description: View Questing statistics of a player
        default: op
    quests.admin.give:
        description: Force a player to take a Quest (Overrides requirements)
        default: op
    quests.admin.quit:
        description: Force a player to quit their current Quest
        default: op
    quests.admin.points:
        description: Set a players Quest Points
        default: op
    quests.admin.takepoints:
        description: Take away a players Quest Points
        default: op
    quests.admin.givepoints:
        description: Give a player Quest Points
        default: op
    quests.admin.pointsall:
        description: Set all players' Quest Points
        default: op
    quests.admin.finish:
        description: Immediately force Quest completion for a player
        default: op
    quests.admin.nextstage:
        description: Immediately force Stage completion for a player
        default: op
    quests.admin.purge:
        description: Clear all Quests data of a player AND BLACKLISTS THEM
        default: op
    quests.admin.reset:
        description: Clear all Quests data of a player
        default: op
    quests.admin.remove:
        description: Remove a completed Quest from a player
        default: op
    quests.admin.togglegui:
        description: Toggle GUI Quest Display on NPC's
        default: op
    quests.admin.reload:
        description: Reload all Quests
        default: op
    quests.editor.editor:
        description: Open Quests Editor
        default: op
    quests.editor.create:
        description: Create new Quests
        default: op
    quests.editor.edit:
        description: Edit Quests
        default: op
    quests.editor.delete:
        description: Delete Quests
        default: op
    quests.editor.events.editor:
        description: Open Events Editor
        default: op
    quests.editor.events.create:
        description: Create new Events
        default: op
    quests.editor.events.edit:
        description: Edit Events
        default: op
    quests.editor.events.delete:
        description: Delete Events
        default: op
    quests.party.create:
        description: Create/Disband Parties
        default: true
    quests.party.join:
        description: Join parties without invitation
        default: op
commands:
    quests:
        description: Quests command
        permission: quests.quests
    questadmin:
        description: Quests admin command
        permission: quests.admin
        aliases: [questsadmin]
    quest:
        description: Quest command
        permission: quests.quest